kind: project
metadata:
  name: nyc-taxi-testgit
spec:
  functions: []
  workflows: []
  artifacts: []
  source: git://github.com/GiladShapira94/project.git#refs/heads/master
  subpath: ''
  origin_url: git://github.com/GiladShapira94/project.git#refs/heads/master
  desired_state: online
  disable_auto_mount: false
